---
- name: test the script 
  hosts: local
  tasks:
    - name: creating ec2 instance 
      ec2:
        key_name: universal
        group_id: sg-02703b50
        region: us-east-1
        instance_type: t2.micro
        image: ami-07ebfd5b3428b6f4d
        wait: yes
        vpc_subnet_id: subnet-1ca4a17b
    - name: fetching instance information
      ec2_instance_info:
        region: us-east-1
        validate_certs: no
   